# Generated by Django 6.0.3 on 2026-03-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_four', models.CharField(max_length=50, unique=True, verbose_name='Code Fournisseur')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom/Raison Sociale')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('ville', models.CharField(blank=True, max_length=50, null=True)),
                ('nif_ou_compte', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Compte Bancaire')),
                ('montant_engage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('annee_ex', models.CharField(max_length=4, verbose_name='Exercice')),
                ('compte', models.CharField(max_length=50, verbose_name='Nomenclature')),
                ('libelle_compte', models.CharField(max_length=255)),
                ('quantite', models.FloatField(default=0)),
                ('prix_unitaire_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prevision', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_engage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reliquat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_app.fournisseur')),
            ],
        ),
    ]
