# Generated by Django 6.0.3 on 2026-03-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.FloatField(default=0)),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('specification', models.TextField(blank=True)),
                ('observation', models.TextField(blank=True)),
            ],
        ),
    ]
