# Generated by Django 6.0.3 on 2026-03-18 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_compte_principal', models.CharField(max_length=50, verbose_name='N° Compte Principale')),
                ('num_sous_compte', models.CharField(max_length=50, verbose_name='N° Sous Compte')),
                ('nom_attache', models.CharField(max_length=100, verbose_name='Attaché')),
                ('comptes', models.CharField(max_length=50, verbose_name='Comptes')),
                ('annee_ex', models.CharField(max_length=50, verbose_name='Année_EX')),
                ('budget_primitive', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('libelle_sous_compte', models.CharField(max_length=255, verbose_name='Libellé')),
                ('budget_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('realisation_budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('mois', models.CharField(max_length=50, verbose_name='Mois')),
                ('dbm_moins', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='DBM_Moins')),
                ('dbm_ajout', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='DBM_Ajout')),
            ],
        ),
        migrations.RemoveField(
            model_name='budget',
            name='date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='montant_ttc',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='prix_unitaire_ttc',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='quantite',
        ),
        migrations.AddField(
            model_name='budget',
            name='montant_realise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='budget',
            name='annee_ex',
            field=models.CharField(max_length=50, verbose_name='Code_EX'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='compte',
            field=models.CharField(max_length=50, verbose_name='Comptes'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='libelle_compte',
            field=models.CharField(max_length=255, verbose_name='Libellé_compte'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='montant_engage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='budget',
            name='prevision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='budget',
            name='reliquat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='budget',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_app.allocationbudget'),
        ),
    ]
