# Generated by Django 6.0.3 on 2026-03-18 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_allocationbudget_remove_budget_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_compte_principal', models.CharField(max_length=50, verbose_name='N° Compte Principale')),
                ('num_sous_compte', models.CharField(max_length=50, verbose_name='N° Sous Compte')),
                ('nom_attache', models.CharField(max_length=100, verbose_name='Attaché')),
                ('comptes', models.CharField(max_length=50, verbose_name='Comptes')),
                ('annee_ex', models.CharField(max_length=50, verbose_name='Année_EX')),
                ('budget_primitive', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('libelle_sous_compte', models.CharField(max_length=255, verbose_name='Libellé')),
                ('budget_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('realisation_budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fournisseur_nom', models.CharField(max_length=100, verbose_name='Fournisseur')),
                ('mois', models.CharField(max_length=50, verbose_name='Mois')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_four', models.CharField(max_length=50, verbose_name='Code_four')),
                ('date_depense', models.DateField(verbose_name='Date')),
                ('num_depense', models.CharField(max_length=50, verbose_name='Numero')),
                ('montant_depense', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_engagement', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reliquat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('compte', models.CharField(max_length=50, verbose_name='Compte')),
                ('objet_depense', models.TextField(verbose_name='Objet')),
                ('annee_ex', models.CharField(max_length=50, verbose_name='Code_EX')),
                ('budget_ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.budget', verbose_name='IDbudget')),
                ('depense_parente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.depense', verbose_name='IDDépenses')),
            ],
        ),
    ]
