# Generated by Django 6.0.3 on 2026-03-18 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_depense_detailsdepense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_recette', models.IntegerField(verbose_name='N°Recette')),
                ('date_recette', models.DateField(verbose_name='Date')),
                ('montant_recette', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Montant')),
                ('annee_ex', models.CharField(max_length=50, verbose_name='Code_EX')),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('nom_totalisateur', models.CharField(max_length=50, verbose_name='Totalisateur')),
                ('nom_service', models.CharField(max_length=50, verbose_name='Service demandeur')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsRecette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, verbose_name='Désignation')),
                ('quantite_recette', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Quantité')),
                ('unite', models.CharField(max_length=50, verbose_name='Unité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Prix Unitaire HT')),
                ('prix_unitaire_ttc', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Prix Unitaire TTC')),
                ('nomenclature', models.CharField(max_length=50, verbose_name='Compte')),
                ('source', models.CharField(max_length=50, verbose_name='Source')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Montant TTC')),
                ('reference_pieces', models.CharField(max_length=50, verbose_name='Référence_pièces')),
                ('ipm', models.CharField(max_length=50, verbose_name='IPM')),
                ('code_recette', models.CharField(max_length=50, verbose_name='Type de recette')),
                ('nom_ipm', models.CharField(max_length=50, verbose_name='Nom_IPM')),
                ('budget_ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.budget', verbose_name='IDbudget')),
                ('recette_parente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.recette', verbose_name='IDRecette')),
            ],
        ),
    ]
