# Generated by Django 6.0.3 on 2026-03-18 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_recette_detailsrecette'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_app.fournisseur'),
        ),
        migrations.AddField(
            model_name='budget',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='budget',
            name='quantite_recette',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='montant_engage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
