# Generated by Django 6.0.3 on 2026-03-19 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0006_budget_fournisseur_budget_montant_paye_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_paiement', models.IntegerField(verbose_name='N° Ordre payment')),
                ('date_payement', models.DateField(verbose_name='Date_pay')),
                ('annee_ex', models.CharField(max_length=50, verbose_name='Code_EX')),
                ('objet_payement', models.CharField(max_length=50, verbose_name='Objet')),
                ('valider_pay', models.BooleanField(default=False, verbose_name='Valider')),
            ],
        ),
        migrations.RemoveField(
            model_name='depense',
            name='fournisseur_nom',
        ),
        migrations.AddField(
            model_name='depense',
            name='dbm_ajout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='depense',
            name='dbm_moins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='depense',
            name='fournisseur',
            field=models.CharField(default='Non spécifié', max_length=50),
        ),
        migrations.AddField(
            model_name='detailsdepense',
            name='dbm_ajout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detailsdepense',
            name='dbm_moins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='budget',
            name='montant_engage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total Engagé'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Cumul Paiements'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='reliquat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Reliquat Disponible'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='annee_ex',
            field=models.CharField(default='', max_length=50, verbose_name='Code_EX'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='comptes',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='depense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='libelle_sous_compte',
            field=models.CharField(default='', max_length=50, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='mois',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='depense',
            name='nom_attache',
            field=models.CharField(default='', max_length=50, verbose_name='Attaché'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='num_compte_principal',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='depense',
            name='num_sous_compte',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='detailsdepense',
            name='annee_ex',
            field=models.CharField(default='', max_length=50, verbose_name='Code_EX'),
        ),
        migrations.AlterField(
            model_name='detailsdepense',
            name='code_four',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='detailsdepense',
            name='compte',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='detailsdepense',
            name='date_depense',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='detailsdepense',
            name='num_depense',
            field=models.CharField(default='', max_length=50, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='detailsdepense',
            name='objet_depense',
            field=models.TextField(default='', verbose_name='Objet'),
        ),
        migrations.CreateModel(
            name='DetailsPayement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon_engagement', models.IntegerField(verbose_name='N°')),
                ('comptes', models.CharField(max_length=50)),
                ('fournisseur', models.CharField(max_length=50)),
                ('date_fact', models.DateField(verbose_name='Date Facture')),
                ('nom_service', models.CharField(max_length=50, verbose_name='Service')),
                ('montant_inscrit', models.CharField(max_length=50, verbose_name='MontantInscrit')),
                ('budget_ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.budget', verbose_name='IDbudget')),
                ('paiement_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.paiement', verbose_name='IDPayement1')),
            ],
        ),
    ]
