# Generated by Django 6.0.3 on 2026-03-19 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0007_paiement_remove_depense_fournisseur_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon_engagement', models.IntegerField(default=0, verbose_name='N°')),
                ('reference_pieces', models.CharField(default='', max_length=50, verbose_name='Référence pièces')),
                ('annee_ex', models.CharField(default='', max_length=50, verbose_name='Code_EX')),
                ('fournisseur', models.CharField(default='', max_length=50, verbose_name='Fournisseur')),
                ('date_engagement', models.DateField(blank=True, null=True, verbose_name='Date Engagement')),
                ('objet_engagement', models.CharField(default='', max_length=50, verbose_name='Objet_Engagement')),
                ('nom_totalisateur', models.CharField(default='', max_length=50, verbose_name='Totalisateur')),
                ('comptes', models.CharField(default='', max_length=50, verbose_name='Comptes')),
                ('nombre_articles', models.IntegerField(default=0, verbose_name='Nombre articles')),
                ('montant_engagement', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant engagement')),
                ('montant_inscrit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant inscrit')),
                ('nom_service', models.CharField(default='', max_length=50, verbose_name='Service demandeur')),
                ('facture', models.BooleanField(default=False, verbose_name='Facturé')),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
            ],
        ),
        migrations.AlterField(
            model_name='detailspayement',
            name='comptes',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='detailspayement',
            name='date_fact',
            field=models.DateField(blank=True, null=True, verbose_name='Date Facture'),
        ),
        migrations.AlterField(
            model_name='detailspayement',
            name='fournisseur',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='detailspayement',
            name='montant_inscrit',
            field=models.CharField(default='', max_length=50, verbose_name='MontantInscrit'),
        ),
        migrations.AlterField(
            model_name='detailspayement',
            name='nom_service',
            field=models.CharField(default='', max_length=50, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='detailspayement',
            name='num_bon_engagement',
            field=models.IntegerField(default=0, verbose_name='N°'),
        ),
        migrations.AlterField(
            model_name='detailsrecette',
            name='code_recette',
            field=models.CharField(default='', max_length=50, verbose_name='Type de recette'),
        ),
        migrations.AlterField(
            model_name='detailsrecette',
            name='designation',
            field=models.CharField(default='', max_length=50, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='detailsrecette',
            name='ipm',
            field=models.CharField(default='', max_length=50, verbose_name='IPM'),
        ),
        migrations.AlterField(
            model_name='detailsrecette',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant TTC'),
        ),
        migrations.AlterField(
            model_name='detailsrecette',
            name='nom_ipm',
            field=models.CharField(default='', max_length=50, verbose_name='Nom_IPM'),
        ),
        migrations.AlterField(
            model_name='detailsrecette',
            name='nomenclature',
            field=models.CharField(default='', max_length=50, verbose_name='Compte'),
        ),
        migrations.AlterField(
            model_name='detailsrecette',
            name='prix_unitaire_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Prix Unitaire HT'),
        ),
        migrations.AlterField(
            model_name='detailsrecette',
            name='prix_unitaire_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Prix Unitaire TTC'),
        ),
        migrations.AlterField(
            model_name='detailsrecette',
            name='quantite_recette',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='detailsrecette',
            name='reference_pieces',
            field=models.CharField(default='', max_length=50, verbose_name='Référence_pièces'),
        ),
        migrations.AlterField(
            model_name='detailsrecette',
            name='source',
            field=models.CharField(default='', max_length=50, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='detailsrecette',
            name='unite',
            field=models.CharField(default='', max_length=50, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='annee_ex',
            field=models.CharField(default='', max_length=50, verbose_name='Code_EX'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_payement',
            field=models.DateField(blank=True, null=True, verbose_name='Date_pay'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='num_paiement',
            field=models.IntegerField(default=0, verbose_name='N° Ordre payment'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='objet_payement',
            field=models.CharField(default='', max_length=50, verbose_name='Objet'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='annee_ex',
            field=models.CharField(default='', max_length=50, verbose_name='Code_EX'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='date_recette',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='montant_recette',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='nom_service',
            field=models.CharField(default='', max_length=50, verbose_name='Service demandeur'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='nom_totalisateur',
            field=models.CharField(default='', max_length=50, verbose_name='Totalisateur'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='num_recette',
            field=models.IntegerField(default=0, verbose_name='N°Recette'),
        ),
        migrations.CreateModel(
            name='DetailsEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='', max_length=50, verbose_name='Désignation')),
                ('specification', models.CharField(default='', max_length=50, verbose_name='Spécification')),
                ('quantite_engagement', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Quantité')),
                ('unite', models.CharField(default='', max_length=50, verbose_name='Unité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Prix Unitaire HT')),
                ('prix_unitaire_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Prix Unitaire TTC')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant TTC')),
                ('observation', models.CharField(default='', max_length=50, verbose_name='Observation')),
                ('compte', models.CharField(default='', max_length=50, verbose_name='Compte')),
                ('bon_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.bonengagement', verbose_name='IDBonEngagement')),
                ('budget_ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.budget', verbose_name='IDbudget')),
            ],
        ),
    ]
