# Generated by Django 6.0.3 on 2026-03-19 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0008_bonengagement_alter_detailspayement_comptes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationGeneralBugdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comptes', models.CharField(default='', max_length=50)),
                ('annee_ex', models.CharField(default='', max_length=50, verbose_name='Année_EX')),
                ('comptes_annee_ex', models.CharField(default='', max_length=50, verbose_name='Comptes + Année_EX')),
                ('libelle_sous_compte', models.CharField(default='', max_length=50, verbose_name='Libellé')),
                ('mois', models.CharField(default='', max_length=50)),
                ('sigle', models.CharField(default='', max_length=50)),
                ('service', models.CharField(default='', max_length=50)),
                ('ville', models.CharField(default='', max_length=50)),
                ('budget_primitive', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('budget_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('realisation_budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('dbm_moins', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('dbm_ajout', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('taux_excurtion', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Taux exécution')),
                ('reste_a', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Reste à')),
                ('disponible', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Disponible')),
                ('budget_ligne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_app.budget', verbose_name='IDbudget')),
            ],
            options={
                'verbose_name': 'Situation Générale Budget',
                'verbose_name_plural': 'Situations Générales Budget',
            },
        ),
    ]
