# Generated by Django 6.0.3 on 2026-03-19 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0009_situationgeneralbugdet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_facture', models.IntegerField(default=0, verbose_name='N° Facture')),
                ('date_fact', models.DateField(blank=True, null=True, verbose_name='Date Facture')),
                ('annee_ex', models.CharField(default='', max_length=50, verbose_name='Code_EX')),
                ('date_livraison', models.DateField(blank=True, null=True, verbose_name='Date_livraison')),
                ('num_bon_livraison', models.IntegerField(default=0, verbose_name='N° Bon_Livraison')),
                ('fournisseur', models.CharField(default='', max_length=50, verbose_name='Fournisseur')),
                ('num_pvr', models.IntegerField(default=0, verbose_name='N°PV')),
                ('montant_facture', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant Facture')),
                ('quantite_facture', models.IntegerField(default=0, verbose_name="Nombre d'articles")),
                ('validé', models.BooleanField(default=False, verbose_name='Engagé')),
                ('payé', models.BooleanField(default=False, verbose_name='Payé')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pv_reception', models.IntegerField(default=0, verbose_name='N° PV Réception')),
                ('date_fact', models.DateField(blank=True, null=True, verbose_name='Date Facture')),
                ('date_reception', models.DateField(blank=True, null=True, verbose_name='Date de Réception')),
                ('annee_ex', models.CharField(default='', max_length=50, verbose_name='Code_EX')),
                ('fournisseur', models.CharField(default='', max_length=50, verbose_name='Fournisseur')),
                ('numero_facture', models.IntegerField(default=0, verbose_name='N° Facture')),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('montant_fact', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant_Fact')),
                ('marche', models.CharField(default='', max_length=50, verbose_name='Marché')),
                ('date_mar', models.DateField(blank=True, null=True, verbose_name='Date Mar')),
                ('montant_pv', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant_PV')),
                ('commission', models.CharField(default='', max_length=50, verbose_name='Commission')),
                ('validé', models.BooleanField(default=False, verbose_name='Validé')),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pv_reception', models.IntegerField(default=0, verbose_name='N° PV Réception')),
                ('date_reception', models.DateField(blank=True, null=True, verbose_name='Date de Réception')),
                ('annee_ex', models.CharField(default='', max_length=50, verbose_name='Code_EX')),
                ('fournisseur', models.CharField(default='', max_length=50, verbose_name='Fournisseur')),
                ('validé', models.BooleanField(default=False, verbose_name='Validé')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon_engagement', models.IntegerField(default=0, verbose_name='N°')),
                ('date_bc', models.DateField(blank=True, null=True, verbose_name='Date de commande')),
                ('annee_ex', models.CharField(default='', max_length=50, verbose_name='Code_EX')),
                ('fournisseur', models.CharField(default='', max_length=50)),
                ('code_ser', models.CharField(default='', max_length=50, verbose_name='Service')),
                ('objet_depense', models.CharField(default='', max_length=50, verbose_name='Objet')),
                ('destinataire_bc', models.CharField(default='', max_length=50, verbose_name='Destinataire')),
                ('totalisateur', models.CharField(default='', max_length=50)),
                ('quantite_facture', models.IntegerField(default=0, verbose_name="Nombre d'articles")),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('budget_ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.budget', verbose_name='IDbudget')),
                ('facture_parente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.facture', verbose_name='IDFacture')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(default='', max_length=50, verbose_name='Compte')),
                ('designation', models.CharField(default='', max_length=50, verbose_name='Désignation')),
                ('specification', models.CharField(default='', max_length=50, verbose_name='Spécification')),
                ('quantite_reception', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Quantité')),
                ('unite', models.CharField(default='', max_length=50, verbose_name='Unité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Prix Unitaire HT')),
                ('prix_unitaire_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Prix Unitaire TTC')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant TTC')),
                ('observation', models.CharField(default='', max_length=50, verbose_name='Observation')),
                ('budget_ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.budget', verbose_name='IDbudget')),
                ('reception_parente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.reception', verbose_name='IDRéception')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_facture', models.IntegerField(default=0, verbose_name='N° Facture')),
                ('date_fact', models.DateField(blank=True, null=True, verbose_name='Date Facture')),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('montant_fact', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant Fact')),
                ('marche', models.CharField(default='', max_length=50, verbose_name='Marché')),
                ('date_mar', models.DateField(blank=True, null=True, verbose_name='Date Mar')),
                ('montant_pv', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant PV')),
                ('commission', models.CharField(default='', max_length=50, verbose_name='Commission')),
                ('budget_ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.budget', verbose_name='IDbudget')),
                ('technique_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.technique', verbose_name='IDTechnique1')),
            ],
        ),
    ]
