# Generated by Django 6.0.3 on 2026-03-19 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0010_facture_reception_technique_detailsfacture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeEnCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_ex', models.CharField(default='', max_length=50, verbose_name='Code_EX')),
                ('valider', models.BooleanField(default=False, verbose_name='Année Active')),
            ],
        ),
        migrations.CreateModel(
            name='Attache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_attache', models.CharField(default='', max_length=100, verbose_name='Nom Attaché')),
            ],
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_chapitre', models.CharField(default='', max_length=50, verbose_name='Code Chapitre')),
                ('libelle_chapitre', models.CharField(default='', max_length=100, verbose_name='Libellé Chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='Cumul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comptes', models.CharField(default='', max_length=50, verbose_name='Comptes')),
                ('annee_ex', models.CharField(default='', max_length=50, verbose_name='Année_EX')),
                ('montant_initial', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('montant_engage', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('montant_realise', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ser', models.CharField(default='', max_length=50, verbose_name='Code Service')),
                ('nom_ser', models.CharField(default='', max_length=100, verbose_name='Nom Service')),
                ('responsable_ser', models.CharField(default='', max_length=100, verbose_name='Responsable')),
                ('recette', models.BooleanField(default=False, verbose_name='Recette')),
                ('depense', models.BooleanField(default=False, verbose_name='Dépense')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciceBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_ex', models.CharField(default='', max_length=50, verbose_name='Année Exercice')),
            ],
        ),
        migrations.CreateModel(
            name='IPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ipm', models.CharField(default='', max_length=50, verbose_name='Code IPM')),
                ('libelle_ipm', models.CharField(default='', max_length=100, verbose_name='Libellé IPM')),
            ],
        ),
        migrations.CreateModel(
            name='MembresCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_membre_commission', models.CharField(default='', max_length=150, verbose_name='Nom du Membre')),
                ('qualite', models.CharField(default='', max_length=100, verbose_name='Qualité / Titre')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature')),
            ],
        ),
        migrations.CreateModel(
            name='ModeReglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_pay', models.CharField(default='', max_length=100, verbose_name='Mode de paiement')),
            ],
        ),
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_mois', models.CharField(default='', max_length=50, verbose_name='Mois')),
            ],
            options={
                'verbose_name_plural': 'Mois',
            },
        ),
        migrations.CreateModel(
            name='NumComptePrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_compte_principal', models.CharField(default='', max_length=50, verbose_name='N° Compte Principal')),
                ('libelle_compte_principal', models.CharField(default='', max_length=100, verbose_name='Libellé')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pay', models.DateField(blank=True, null=True, verbose_name='Date Paiement')),
                ('montant_pay', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant')),
                ('mode_pay', models.CharField(default='', max_length=50, verbose_name='Mode de paiement')),
                ('objet_payement', models.CharField(default='', max_length=200, verbose_name='Objet')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeRecette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_periode_recette', models.DateField(blank=True, null=True, verbose_name='Début Période')),
                ('fin_periode_recette', models.DateField(blank=True, null=True, verbose_name='Fin Période')),
                ('compte', models.CharField(default='', max_length=50, verbose_name='Compte')),
                ('code_recette', models.CharField(default='', max_length=50, verbose_name='Code Recette')),
            ],
        ),
        migrations.CreateModel(
            name='PlanComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_compte', models.CharField(default='', max_length=50, verbose_name='N° Compte')),
                ('libelle_compte', models.CharField(default='', max_length=150, verbose_name='Libellé Compte')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_role', models.CharField(default='', max_length=100, verbose_name='Nom du Rôle')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_section', models.IntegerField(default=0, verbose_name='N° Section')),
                ('libelle_section', models.CharField(default='', max_length=100, verbose_name='Libellé Section')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(default='', max_length=100, verbose_name='Nom Service')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_source', models.CharField(default='', max_length=100, verbose_name='Source de financement')),
            ],
        ),
        migrations.CreateModel(
            name='TypeBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(default='', max_length=50, verbose_name='Code Type')),
                ('libelle_type', models.CharField(default='', max_length=100, verbose_name='Libellé Type')),
            ],
        ),
        migrations.CreateModel(
            name='TypesDeComptes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_compte', models.CharField(default='', max_length=100, verbose_name='Type de Compte')),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_unite', models.CharField(default='', max_length=50, verbose_name='Unité')),
            ],
        ),
        migrations.RemoveField(
            model_name='produit',
            name='compte',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='quantite',
        ),
        migrations.AddField(
            model_name='produit',
            name='famille',
            field=models.CharField(default='', max_length=50, verbose_name='Famille'),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_unitaire_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_unitaire_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='produit',
            name='reference_produit',
            field=models.CharField(default='', max_length=50, verbose_name='Référence'),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_actuel',
            field=models.IntegerField(default=0, verbose_name='Stock Actuel'),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_initial',
            field=models.IntegerField(default=0, verbose_name='Stock Initial'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='designation',
            field=models.CharField(default='', max_length=100, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='specification',
            field=models.TextField(blank=True, default='', verbose_name='Spécification'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(default='', max_length=50, verbose_name='Unité'),
        ),
        migrations.CreateModel(
            name='DBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dbm', models.DateField(blank=True, null=True, verbose_name='Date DBM')),
                ('montant_dbm', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant DBM')),
                ('comptes_de', models.CharField(default='', max_length=50, verbose_name="Comptes d'origine")),
                ('compte_fi', models.CharField(default='', max_length=50, verbose_name='Comptes destinataire')),
                ('annee_ex', models.CharField(default='', max_length=50, verbose_name='Année_EX')),
                ('budget_ligne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_app.budget', verbose_name='IDbudget')),
            ],
            options={
                'verbose_name': 'DBM',
                'verbose_name_plural': 'DBMs',
            },
        ),
        migrations.CreateModel(
            name='FicheControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_fiche', models.IntegerField(default=0, verbose_name='N° Fiche')),
                ('date_fiche', models.DateField(blank=True, null=True, verbose_name='Date Fiche')),
                ('objet_fiche', models.CharField(default='', max_length=200, verbose_name='Objet')),
                ('montant_fiche', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant')),
                ('annee_ex', models.CharField(default='', max_length=50, verbose_name='Année_EX')),
                ('valider', models.BooleanField(default=False, verbose_name='Validé')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.fournisseur', verbose_name='Fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetCompare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comptes', models.CharField(default='', max_length=50, verbose_name='Comptes')),
                ('libelle_sous_compte', models.CharField(default='', max_length=150, verbose_name='Libellé')),
                ('annee_ex', models.CharField(default='', max_length=50, verbose_name='Année_EX')),
                ('budget_primitive', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('dbm_ajout', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('dbm_moins', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('realisation_budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reliquat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('compte_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.numcompteprincipal', verbose_name='NumComptePrincipal')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='compte_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_app.numcompteprincipal', verbose_name='Compte Principal'),
        ),
        migrations.AddField(
            model_name='numcompteprincipal',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_app.section', verbose_name='Section'),
        ),
        migrations.CreateModel(
            name='SousCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sous_compte', models.CharField(default='', max_length=50, verbose_name='N° Sous-Compte')),
                ('libelle_sous_compte', models.CharField(default='', max_length=100, verbose_name='Libellé Sous-Compte')),
                ('nom_type_compte', models.CharField(default='', max_length=100, verbose_name='Nom Type Compte')),
                ('annee_exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_app.anneeencours', verbose_name='Année_EX')),
                ('attache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_app.attache', verbose_name='Nom Attaché')),
                ('compte_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_app.numcompteprincipal', verbose_name='Compte Principal')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant Prévu')),
                ('montant_reel', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant Réel')),
                ('ecart', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Écart')),
                ('annee_exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.anneeencours', verbose_name='Année_EX')),
                ('mois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.mois', verbose_name='Mois')),
                ('compte_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.souscompte', verbose_name='Comptes')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='sous_compte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_app.souscompte', verbose_name='Sous-Compte'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='', max_length=50, verbose_name='Référence')),
                ('unite', models.CharField(default='', max_length=50, verbose_name='Unité')),
                ('quantite_stock', models.IntegerField(default=0, verbose_name='Quantité Stock')),
                ('prix_unitaire_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('montant_stock', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('annee_exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.anneeencours', verbose_name='Année_EX')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.produit', verbose_name='Désignation')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.source', verbose_name='Source')),
                ('type_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.typebudget', verbose_name='NomTypeBudget')),
            ],
        ),
        migrations.AddField(
            model_name='numcompteprincipal',
            name='type_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_app.typebudget', verbose_name='Type de Budget'),
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(default='', max_length=100, verbose_name="Nom d'utilisateur")),
                ('mot_de_passe', models.CharField(max_length=100, verbose_name='Mot de passe')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.role', verbose_name='Rôle')),
            ],
        ),
    ]
